package com.institute.workforce_tracking.entity;

import java.time.Instant;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;

/**
 * Base class for all JPA entities in the system.
 *
 * <p>Provides the identity (primary key) and audit timestamps that every table
 * needs, so individual entities don't repeat this boilerplate. The timestamps
 * are populated automatically by Spring Data JPA auditing (enabled via
 * {@code JpaAuditingConfig}).</p>
 *
 * <p>Marked {@code @MappedSuperclass}: its fields are mapped into each
 * subclass's table, but it is not itself a table. It is abstract because it is
 * never persisted on its own — only concrete entities that extend it are.</p>
 */
@Getter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    /**
     * Surrogate primary key, generated by the database (auto-increment).
     * No setter: the persistence provider assigns it.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** When the row was first persisted. Set once, never updated. */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** When the row was last modified. Updated on every save. */
    @LastModifiedDate
    @Column(nullable = false)
    private Instant updatedAt;
}